10/1/90:
If another machine is being updated, and a user tries to turn
something in, init_1 will return an error, making multi_set_course
drop the connection.  The machine being updated never figures out that
it's no longer being updated, and refuses to be updated again because
it's already in the process of being updated.

Solution (?): Make init_1 and other calls not return an error when a
server is calling.

